[package]
name = "sciplings"
version = "0.1.0"
edition = "2021"

[dependencies]
russcip = { version = "0.8.2" }
scip-sys = { version = "0.1.13" }
rayon = "1.10.0"
clap = { version = "4.5.19", features = ["derive"] }